config.yaml, devConfig.yaml, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/test/java/io/supertokens/storage/postgresql/test/ConfigTest.java
just refactor the func `addPrefixToTableName` to `addSchemaAndPrefixToTableName`, which add schema to table.
https://github.com/supertokens/supertokens-docker-postgresql/pull/2
=> feature: support scheme tables

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/SessionQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
Adding delete user functionality
- supertokens/supertokens-core#350
- supertokens/supertokens-plugin-interface#28
Tested in core repo
N/A
=> Implementing delete user

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/Start.java, src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java
- Catching `StorageTransactionLogicException` in transaction helper function for retries.
- Added a new test in PostgreSQL plugin which uses passwordless recipe to simulate a deadlock which should be retried
- https://github.com/supertokens/supertokens-core/issues/373
- Added a new test
None
=> fixes: Takes into account StorageTransactionLogicException when doing retries in transaction

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java
Added an index on device_id_hash to the codes table. In MySQL this is created automatically.
- Possibly related to: https://github.com/supertokens/supertokens-core/issues/373
Manual tests
In PR 
=> feat: adding index on device_id_hash for codes

src/main/java/io/supertokens/storage/postgresql/Start.java
Fix fallthrough while choosing the isolation level
This was caught by CI/CD, no new tests were necessary
Internal change
=> fix: isolation level fallthrough

CHANGELOG.md, src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java, src/main/java/io/supertokens/storage/postgresql/output/CustomLayout.java, src/main/java/io/supertokens/storage/postgresql/output/LayoutWrappingEncoder.java, src/main/java/io/supertokens/storage/postgresql/output/Logging.java, src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java, src/test/java/io/supertokens/storage/postgresql/test/InMemoryDBTest.java, src/test/java/io/supertokens/storage/postgresql/test/LoggingTest.java, src/test/java/io/supertokens/storage/postgresql/test/TableCreationTest.java, src/test/java/io/supertokens/storage/postgresql/test/Utils.java
There were a few memery leaks in the core during testing and some of them were related to how we setup loggers and connection to the storage layer. So to fix that, we had to make some changes to this plugin.
- https://github.com/supertokens/supertokens-postgresql-plugin/issues/34
None
=> Fixes issue with memory leak during testing

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserMetadataQueries.java, src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java
Adds user metadata support
- #381 
- #239 
Tests were added in the core repo.
TODO
=> feat(user_metadata): adds support for usermetadata

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json
Updates CHANGELOG.md, build.gradle and pluginInterface.json
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/38
- none
- none
=> chore:  updates

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
- Adds userRoles support
- https://github.com/supertokens/supertokens-core/pull/414
=> feat(user-roles): adds userRoles recipe support

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/SessionQueries.java
=> feat: returns only non expired session handles for user

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserIdMappingQueries.java
Adds userIdMapping support
- https://github.com/supertokens/supertokens-core/issues/463
- Run core tests
- none
=> feat: adds userIdMapping support

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserIdMappingQueries.java
- https://github.com/supertokens/supertokens-core/pull/489
=> feat: Userid mapping updates

src/main/java/io/supertokens/storage/postgresql/queries/UserIdMappingQueries.java
=> fixes getUserIdMappingWithUserIds

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/Config.java, src/main/java/io/supertokens/storage/postgresql/output/Logging.java, src/test/java/io/supertokens/storage/postgresql/test/LogLevelTest.java, src/test/java/io/supertokens/storage/postgresql/test/LoggingTest.java
Changes as per new plugin interface to add log level feature
- https://github.com/supertokens/supertokens-core/issues/494
- Checking logger is not logging when different log levels are enabled
=> feat: Adds Log level feature

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
=> feat: adds third party tenant mapping functions

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json
- https://github.com/supertokens/supertokens-core/issues/525
=> updates dependencies

CHANGELOG.md, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/main/java/io/supertokens/storage/postgresql/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
feat: Storage layer to monitor active users
- https://github.com/supertokens/supertokens-core/pull/585
=> feat: Storage layer to monitor active users

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java, src/test/java/io/supertokens/storage/postgresql/test/ExceptionParsingTest.java
Email verification, Passwordless and Thirdparty related schema changes and updated queries
=> fix: Multitenant schema changes

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserIdMappingQueries.java
=> fix: to support PR comments on core

src/main/java/io/supertokens/storage/postgresql/Start.java, src/test/java/io/supertokens/storage/postgresql/test/StorageLayerTest.java
Fix failing tests
- https://github.com/supertokens/supertokens-core/issues/597
=> test: Fix failing tests

src/test/java/io/supertokens/storage/postgresql/test/ExceptionParsingTest.java
=> fix: Multitenant emailpassword

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
=> feat: dashboard search support

src/test/java/io/supertokens/storage/postgresql/test/ExceptionParsingTest.java
=> fix: thirdparty storage

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java, src/test/java/io/supertokens/storage/postgresql/test/ExceptionParsingTest.java
=> fix: Multitenant thirdparty changes for update email

src/test/java/io/supertokens/storage/postgresql/test/ExceptionParsingTest.java
=> fix: Multitenant emailverification storage

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/SessionQueries.java, src/test/java/io/supertokens/storage/postgresql/test/ConfigTest.java, src/test/java/io/supertokens/storage/postgresql/test/InMemoryDBTest.java
=> fix: Multitenant session

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java
key value changes required for refresh token signing key
=> fix: Multitenant session changes

src/test/java/io/supertokens/storage/postgresql/test/InMemoryDBTest.java
=> test: fix exception list in test definition

src/main/java/io/supertokens/storage/postgresql/Start.java
=> fix: increase transaction retry count&timeout

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/JWTSigningQueries.java, src/test/java/io/supertokens/storage/postgresql/test/ExceptionParsingTest.java
=> fix: Multitenant jwt

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
=> fix: Multitenant General Queries

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/DashboardQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
- https://github.com/supertokens/supertokens-core/issues/546
=> fix: Multitenant dashboard

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/TOTPQueries.java, src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java, src/test/java/io/supertokens/storage/postgresql/test/StorageLayerTest.java
- https://github.com/supertokens/supertokens-core/issues/546
=> fix: Multitenant totp

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java, src/test/java/io/supertokens/storage/postgresql/test/ExceptionParsingTest.java
=> fix: Tenantid in userobjects

src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
user_id is CHAR(36) and it's returning userId like "userId ...lots of spaces here..." for some tests
=> fix: Test fixes

src/test/java/io/supertokens/storage/postgresql/test/multitenancy/TestUserPoolIdChangeBehaviour.java
Test to see the user works as expected after a userpool id change
=> fix: Userpool test

src/main/java/io/supertokens/storage/postgresql/Start.java
=> fix: Delete nonauth user

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
=> fix: Config validation

config.yaml, devConfig.yaml
=> fix: config per tenant, per app annotations

CHANGELOG.md
=> chore: clarify migration steps in changelog

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/annotations/ConnectionPoolProperty.java, src/main/java/io/supertokens/storage/postgresql/annotations/IgnoreForAnnotationCheck.java, src/main/java/io/supertokens/storage/postgresql/annotations/NotConflictingWithinUserPool.java, src/main/java/io/supertokens/storage/postgresql/annotations/UserPoolProperty.java, src/main/java/io/supertokens/storage/postgresql/config/Config.java, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/test/java/io/supertokens/storage/postgresql/test/ConfigTest.java, src/test/java/io/supertokens/storage/postgresql/test/multitenancy/StorageLayerTest.java
=> fix: config annotation

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/Config.java
=> fix: added setLogLevels

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
=> fix: fkey names

src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java, src/main/java/io/supertokens/storage/postgresql/utils/Utils.java
Added tables to support Oauth2.0
https://github.com/supertokens/supertokens-core/issues/582
=> feat: added tables to support oAuth2

CHANGELOG.md, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/DashboardQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/JWTSigningQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/SessionQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/TOTPQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserIdMappingQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserMetadataQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
=> fix: Fkey indexes

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
Added helper methods to insert oauth2 Queries
- https://github.com/supertokens/supertokens-core/issues/582
=> helper methods to insert Oauth2 queries

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
Added queries to support to create and get in Oauth2_scopes schema
- https://github.com/supertokens/supertokens-core/issues/582
=> feat: createOauth2scope queries

CHANGELOG.md, src/main/java/io/supertokens/storage/postgresql/Start.java
=> fix: increased retry count

src/main/java/io/supertokens/storage/postgresql/ProcessState.java, src/main/java/io/supertokens/storage/postgresql/Start.java, src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java
=> fix: deadlock

src/main/java/io/supertokens/storage/postgresql/Start.java, src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java
=> fix: exponential backoff in transaction retry

src/test/java/io/supertokens/storage/postgresql/test/SuperTokensSaaSSecretTest.java, src/test/java/io/supertokens/storage/postgresql/test/httpRequest/HttpRequestForTesting.java, src/test/java/io/supertokens/storage/postgresql/test/httpRequest/HttpRequestMocking.java, src/test/java/io/supertokens/storage/postgresql/test/httpRequest/HttpResponseException.java
=> fix: saas secret test

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
=> fix: appid fkey test

src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java, src/main/java/io/supertokens/storage/postgresql/ResourceDistributor.java, src/main/java/io/supertokens/storage/postgresql/Start.java
=> fix: remove instance in close

src/main/java/io/supertokens/storage/postgresql/Start.java
=> fix: hikari logging

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/test/java/io/supertokens/storage/postgresql/test/ConfigTest.java, src/test/java/io/supertokens/storage/postgresql/test/InMemoryDBTest.java, src/test/java/io/supertokens/storage/postgresql/test/TableCreationTest.java, src/test/java/io/supertokens/storage/postgresql/test/TestingProcessManager.java, src/test/java/io/supertokens/storage/postgresql/test/httpRequest/HttpRequestForTesting.java, src/test/java/io/supertokens/storage/postgresql/test/multitenancy/StorageLayerTest.java
=> fix: Config normalisation

src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java, src/main/java/io/supertokens/storage/postgresql/Start.java, src/test/java/io/supertokens/storage/postgresql/test/TestMainThread.java
=> fix: main thread fix

src/main/java/io/supertokens/storage/postgresql/output/Logging.java
=> fix: logging fix

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
- https://github.com/supertokens/supertokens-node/pull/471
=> fix: app id in user id queries

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
=> fix: null pointer issue for user that belongs to no tenant

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/SessionQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserMetadataQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
=> updates to function

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java
=> changes for password reset flow

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java, src/test/java/io/supertokens/storage/postgresql/test/ExceptionParsingTest.java
=> fix: user pagination

src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/test/java/io/supertokens/storage/postgresql/test/AccountLinkingTests.java
=> fix: plugin interface fix

src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/test/java/io/supertokens/storage/postgresql/test/AccountLinkingTests.java
=> fix: External userid

src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
=> fix: fkey constraint for primary_or_recipe_user_id

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
=> fix: account linking stats

src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
=> fix: fixing tenant association

src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
=> fix: allow user disassociation from all tenant

src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java, src/test/java/io/supertokens/storage/postgresql/test/StorageLayerTest.java
=> fix: deadlock and storage tests

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/MfaQueries.java
=> fix: changes as per plugin interface

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
=> fix: query fix

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java
=> fix: email verification with user id mapping

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
=> fix: fixes call to getPrimaryUserInfoForUserIds_Transaction

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/Config.java, src/main/java/io/supertokens/storage/postgresql/utils/ConfigMapper.java
=> fix: core config type validation

src/main/java/io/supertokens/storage/postgresql/utils/ConfigMapper.java
=> fix: null handling in config mapper

src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/multitenancy/MfaSqlHelper.java, src/main/java/io/supertokens/storage/postgresql/queries/multitenancy/TenantConfigSQLHelper.java, src/test/java/io/supertokens/storage/postgresql/test/AccountLinkingTests.java, src/test/java/io/supertokens/storage/postgresql/test/LoggingTest.java, src/test/java/io/supertokens/storage/postgresql/test/SuperTokensSaaSSecretTest.java, src/test/java/io/supertokens/storage/postgresql/test/multitenancy/StorageLayerTest.java, src/test/java/io/supertokens/storage/postgresql/test/multitenancy/TestUserPoolIdChangeBehaviour.java
=> fix: mfa changes

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/main/java/io/supertokens/storage/postgresql/output/CustomLayout.java, src/main/java/io/supertokens/storage/postgresql/output/Logging.java, src/main/java/io/supertokens/storage/postgresql/utils/Utils.java, src/test/java/io/supertokens/storage/postgresql/test/LoggingTest.java
This PR removes db password from being logged.
- https://github.com/supertokens/supertokens-core/issues/907
=> fix: remove db password from logs

CHANGELOG.md, src/main/java/io/supertokens/storage/postgresql/Start.java, src/test/java/io/supertokens/storage/postgresql/test/DbConnectionPoolTest.java
=> fix: Connection pool issue

src/test/java/io/supertokens/storage/postgresql/test/DbConnectionPoolTest.java
=> fix: cicd tests

src/test/java/io/supertokens/storage/postgresql/test/LoggingTest.java
=> fix: logging test

src/test/java/io/supertokens/storage/postgresql/test/DbConnectionPoolTest.java
=> fix: flaky test

CHANGELOG.md, build.gradle, config.yaml, devConfig.yaml, src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/test/java/io/supertokens/storage/postgresql/test/DbConnectionPoolTest.java, src/test/java/io/supertokens/storage/postgresql/test/SuperTokensSaaSSecretTest.java
=> fix: connection pool test and idle configs

CHANGELOG.md, build.gradle, implementationDependencies.json
- https://github.com/supertokens/supertokens-core/issues/926
=> fix: vulnerability fix

build.gradle, implementationDependencies.json
=> fix: dependencies

build.gradle, implementationDependencies.json
=> fix: version update

build.gradle, src/test/java/io/supertokens/storage/postgresql/test/OneMillionUsersTest.java
=> fix: cicd test

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/SessionQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserIdMappingQueries.java
=> fix: backports for core 8.0

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/SessionQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserIdMappingQueries.java
=> fix: backports to core 7.0

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/SessionQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserIdMappingQueries.java
=> fix: backport to core 6.0

CHANGELOG.md, build.gradle, implementationDependencies.json
- https://github.com/supertokens/supertokens-core/issues/926
=> fix: vulnerability fix (backport to 5.0)

.circleci/doOneMillionUsersTests.sh, .circleci/doTests.sh
=> fix: gradle.properties in tests

src/test/java/io/supertokens/storage/postgresql/test/OneMillionUsersTest.java, src/test/java/io/supertokens/storage/postgresql/test/Utils.java
=> fix: Test fix

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/OAuthQueries.java
=> fix: revoke

.circleci/config.yml, src/main/java/io/supertokens/storage/postgresql/queries/OAuthQueries.java
=> ci: fix ci issues

src/main/java/io/supertokens/storage/postgresql/QueryExecutorTemplate.java, src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/TOTPQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserIdMappingQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserMetadataQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java, src/test/java/io/supertokens/storage/postgresql/test/OneMillionUsersTest.java
=> fix: bulk import fixes

src/main/java/io/supertokens/storage/postgresql/Start.java
=> fix: fixing tests by proper exception handling

src/test/java/io/supertokens/storage/postgresql/test/OneMillionUsersTest.java
=> fix: changing the number of users to be imported in the tests

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/output/CustomLayout.java, src/main/java/io/supertokens/storage/postgresql/output/Logging.java
=> fix: structured logging

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/QueryExecutorTemplate.java, src/main/java/io/supertokens/storage/postgresql/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/SessionQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/TOTPQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserIdMappingQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserMetadataQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
- Fixes StorageTransactionLogicException in bulk import when not using userRoles and totpDevices in import json.
- Additional null and empty checks to avoid invalid syntax queries
latest branch (`git branch --all`) whose `X.Y` is greater than the latest …
=> fix: null and empty checks to avoid DB exception because of invalid syntax

pluginInterfaceSupported.json
=> fix: plugin supported version

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
additional null and empty checks
=> feat: bulk migration returns userids

src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/WebAuthNQueries.java
=> fix: bulk migration webauthn search

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
=> fix: bulk migration account linking test fixes

CHANGELOG.md, build.gradle
=> fix: upgrade tomcat-embed-core

.github/helpers/docker/Dockerfile, .github/helpers/docker/docker-entrypoint.sh, startDb.sh
=> fix: for release 6.0

.github/helpers/docker/Dockerfile, .github/helpers/docker/docker-entrypoint.sh, CHANGELOG.md, build.gradle, startDb.sh
=> fix: for backport 8.0
