supertokens/supertokens-postgresql-plugin

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
- renames `addPermissionToRole_Transaction` -> `addPermissionToRoleOrDoNothingIfExists_Transaction`
- https://github.com/supertokens/supertokens-plugin-interface/pull/35
- run core tests which use addPermissionToRoleOrDoNothingIfExists_Transaction`
- none
=> fix: renames addRoleToPermission function

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
- Adds functions for addUserRole api
- https://github.com/supertokens/supertokens-core/pull/423
- none
=> feat: adds functions for setting a role for a user and retriving user roles

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
Updates plugin interface functions due to the discussion [here](https://github.com/supertokens/supertokens-core/issues/382#issuecomment-1102458937)
- https://github.com/supertokens/supertokens-core/issues/382#issuecomment-1102458937
Run core tests
- none
- To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.~~
- none
=> fix: updates plugin interface functions

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
Adds support for the removeUserRoleAPI and tests
- https://github.com/supertokens/supertokens-core/pull/426
- Ran core tests
- none
=> feat: adds doesRoleExist_transaction and deleteUserRole_transaction

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
Adds query and storage-related functions for the getUsersForRoleAPI
- https://github.com/supertokens/supertokens-core/pull/414
- Added core tests
- none
- none
=> feat: adds getUsersForRoleAPI functions

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
Adds functions for RemovePermissionFromRoleAPI
- https://github.com/supertokens/supertokens-core/pull/433
- adds core tests
- none
=> feat: adds RemovePermissionsFromRoleAPI

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
- Adds query and plugin function for the GetRolesForPermissionAPI
- https://github.com/supertokens/supertokens-core/pull/434
- core tests
- none
- none
=> feat: adds getRolesForPermissionAPI function

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
(Adds Query and plugin function for deleteAllRolesForUser
- https://github.com/supertokens/supertokens-core/pull/438
Run core tests
- none
- none
=> feat: adds deleteAllRolesForUser functions

src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java
Fixed query that shouldn't contain recipe_id
=> fix: Multitenant ep fix

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/Config.java
Made `Loading PostgreSQL config` to not log on console for base tenant.
=> fix: Startup log

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
Added new unique constraint on name, app_id columns of oauth2_client table
- https://github.com/supertokens/supertokens-core/issues/582
=> Fix: add constraint on client name

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java, src/test/java/io/supertokens/storage/postgresql/test/multitenancy/TestUserPoolIdChangeBehaviour.java
=> fix: remove UserInfo class

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
=> fix: multitenant user association with account linking

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
=> fix: remove con reuse

src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
=> fix: index updates

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserIdMappingQueries.java
=> fix: useridmapping functions

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/TOTPQueries.java, src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java, src/test/java/io/supertokens/storage/postgresql/test/StorageLayerTest.java
- https://github.com/supertokens/supertokens-core/issues/554
- https://github.com/supertokens/supertokens-core/pull/651
=> fix: created_at in totp devices

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserIdMappingQueries.java
- https://github.com/supertokens/supertokens-core/issues/872
=> fix: email verified in login methods

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
- https://github.com/supertokens/supertokens-core/issues/554
- https://github.com/supertokens/supertokens-core/pull/651
=> fix: mfa stats

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
Adds an index for foreign key in app_id_to_user_id table.
- https://github.com/supertokens/supertokens-core/issues/887
=> fix: add primary_user_id index to app_id_to_user_id

CHANGELOG.md, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/SessionQueries.java
- Adds a new `useStaticKey` param to `updateSessionInfo_Transaction`
- This enables smooth switching between `useDynamicAccessTokenSigningKey` settings by allowing refresh calls to
change the signing key type of a session
- core: https://github.com/supertokens/supertokens-core/pull/909
- plugin-interface: https://github.com/supertokens/supertokens-plugin-interface/pull/136
- postgresql-plugin: https://github.com/supertokens/supertokens-postgresql-plugin/pull/180
- mysql-plugin: https://github.com/supertokens/supertokens-mysql-plugin/pull/88
- mongodb-plugin: https://github.com/supertokens/supertokens-mongodb-plugin/pull/31
- node: https://github.com/supertokens/supertokens-node/pull/782
Done in core PR
Done in core PR
- To know which one it is, run find the latest …
=> feat: Add support to update the signing key type of a session

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java, src/test/java/io/supertokens/storage/postgresql/test/AccountLinkingTests.java, src/test/java/io/supertokens/storage/postgresql/test/DbConnectionPoolTest.java, src/test/java/io/supertokens/storage/postgresql/test/multitenancy/StorageLayerTest.java, src/test/java/io/supertokens/storage/postgresql/test/multitenancy/TestUserPoolIdChangeBehaviour.java
- Implements `deleteAllUserRoleAssociationsForRole`
- Drops `(app_id, role)` foreign key constraint on `user_roles` table
- https://github.com/supertokens/supertokens-core/issues/941
- If no such branch exists, then create one from the latest …
=> fix: fixes storage handling for non-auth recipes

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java, src/test/java/io/supertokens/storage/postgresql/test/Utils.java, src/test/java/io/supertokens/storage/postgresql/test/multitenancy/StorageLayerTest.java, src/test/java/io/supertokens/storage/postgresql/test/multitenancy/TestForNoCrashDuringStartup.java
- https://github.com/supertokens/supertokens-core/issues/982
=> fix: core db crash

.idea/gradle.xml, .idea/misc.xml, .idea/vcs.xml, CHANGELOG.md, src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/multitenancy/TenantConfigSQLHelper.java, src/test/java/io/supertokens/storage/postgresql/test/multitenancy/StorageLayerTest.java
=> feat: multitenancy dashboard

CHANGELOG.md, build.gradle, src/test/java/io/supertokens/storage/postgresql/test/multitenancy/TestForNoCrashDuringStartup.java
=> fix: tests

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
Fixing slow query for users count
=> fix: slow query fix

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/test/java/io/supertokens/storage/postgresql/test/OneMillionUsersTest.java
Adds index for MAU
- https://github.com/supertokens/supertokens-core/issues/994
=> fix: index for MAU

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/OAuthQueries.java
=> fix: logout queries

src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/queries/OAuthQueries.java
Simplifying jti + comma handling in database.
=> fix: jti listing

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/postgresql/BulkImportProxyConnection.java, src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java, src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java, src/main/java/io/supertokens/storage/postgresql/QueryExecutorTemplate.java, src/main/java/io/supertokens/storage/postgresql/Start.java, src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java, src/main/java/io/supertokens/storage/postgresql/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/SessionQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/TOTPQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserIdMappingQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserMetadataQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java, src/test/java/io/supertokens/storage/postgresql/test/OneMillionUsersTest.java
=> feat: multithreaded bulk import

src/test/java/io/supertokens/storage/postgresql/test/multitenancy/TestForNoCrashDuringStartup.java
=> fix: Fix tests

src/main/java/io/supertokens/storage/postgresql/queries/SessionQueries.java
=> fix: session queries

CHANGELOG.md, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/SessionQueries.java
The lack of index on `session_info`'s `(app_id, user_id)` was causing performance issues at one of the users, so here it goes.
- If no such branch exists, then create …
=> fix: add index for session_info on user_id, app_id

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
=> fix: slow queries for account linking

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java
add tcpKeepAlive to connectionPool config
=> fix: add tcpKeepAlive to connectionPool config

.github/helpers/docker/Dockerfile, .github/helpers/docker/docker-entrypoint.sh, build.gradle, startDb.sh
=> fix: for backport 7.0.
